slovar = {
   "TAPE ": "",
   "15OZ NEOPEREN COATED SALMON": "",
   "17OZ SILICONE FABRIC": "",
   "24OZ NEOPRENE COATED YELLOW": "",
   "18OZ FABRIC 60'X50YDS": "",
   "24OZ WEAVELOCK ORANGE": "",
   "17OZ SILICONE FABRIC (PREMIER)": "",
   "17OZ PTFE FABRIC 60'X50YDS": "",
   "SCRIM 40'X50YDS": "",
   "TYPE 75 1/2 ROLL DUCT WRAP": "",
   "OZ FABRIC": "",
   "ALUMINUM SR 45 DEG ELBOW": "",
   "45 DEG ALUMINUM ELBOW": "",
   "PRECISION CUT ALUMINUM": "",
   "ALUM PRECISIONFIT ENDCAP": "",
   "ALUMEC PRESICIONFIT ENDCAP": "",
   "NOT USE": "",
   "ALUMUNIM PRESCISIONFIT EC": "",
   "ALUM PRESICIONFIT ENDCAP": "",
   "ALUMINUNM LR 90 DEG ELBOW": "",
   "CUT & ROLL ALUM JACKET": "",
   "ALUMINUM LR 90 DEG ELBOW": "",
   "ALUMINUM 45 DEG ELBOW": "",
   "ALUMINUM SR 90 DEG ELBOW": "",
   "SCREWS (SABER)": "",
   "O.D. Y-STRAINER": "",
   "STAINLESS JKT": "",
   "FOAMGLASS LR 90 DEG PLN": "",
   "DUCT LINER": "",
   "PIPE CALIPER": "",
   "THERM SEAM SEAL": "",
   "TUBOLIT SSL": "",
   "TUBOLIT SEAM SE": "",
   "TUBOLIT SEAM SEAL": "",
   "THERMA SEAM SEAL": "",
   "TUBOLIT SEMISLIT": "",
   "TUBOLIT": "",
   "THERMA-CEL": "",
   "TUBLOIT P/C": "",
   "DEXTER BONING KNIFE (THICK)": "",
   "ASJ/SSL": "",
   "FIBERGLASS ASJ/SSL": "",
   "FG APT-PLUS": "",
   "FG ASJ/ASJ OC": "",
   "FG ASJ SSL OCt": "",
   "FG SSL OC": "",
   "FAG OCR": "",
   "FAG AS SISAL OCR": "",
   "OCR FIBERGLASS": "",
   "ASJ SSL OC": "",
   "OC FG ASJ SSL": "",
   "FG ASJ OC": "",
   "FAG AS SSL OC": "",
   "FAG AS OCR": "",
   "O.C FG ASJ SSLrt": "",
   "O.C FG ASJ SSL": "",
   "O.C FIBERGLASS": "",
   "FG ASJ SSL OC": "",
   "OC FIBERGLASS": "",
   "OC FG ASJ": "",
   "FIBERGLASS": "",
   "FG ASJ SSL": "",
   "FG OC": "",
   "FAG ASJ SSL OC": "",
   "FAG AS SISAL OC": "",
   "THERMAFIBER": "",
   "ARMFLX TAPE": "",
   "GAL WHITE WATER BASE ARMAFLEX": "",
   "ARMAFLEX SHTS": "",
   "ROLL ARMAFLEX": "",
   "ARMAFLEX ROLL": "",
   "TYPE ENDER WRAP": "",
   "TYPE WRAP": "",
   "TYPE DUCT WRAP": "",
   "TYPE WHITE VINYL": "",
   "TYPE": "",
   "TYPE VINYL": "",
   "K-FLEX": "",
   "K-FLEX SSL": "",
   "ARMAFLEX SSL": "",
   "ARM SHEET": "",
   "ARMAFLEX SHEET": "",
   "FSK BOARD": "",
   "FSK BDS": "",
   "lb density": "",
   "ASJ BOARDS": "",
   "PLAIN BOARD": "",
   "ASJ BOARD": "",
   "PLAIN ASJ BOARD": "",
   "ASJ BOARDS ": "",
   "MICROFLEX ASJ": "",
   "MICROFLEX": "",
   "JM MICROFLEX": "",
   "ASJ MIN WOOL BENDA BOARD": "",
   "FSK BEND A BOARD MINERAL": "",
   "FSK MINERAL WOOL PIPE/TANK": "",
   "MINERAL WOOL FPS BOARD": "",
   "LB TRIFOLIATE": "",
   "GAL VIMASCO WHITE VAPOR": "",
   "GAL CP-11 SPRAY BRUSH WHITE": "",
   "GAL MIRACLE GLUE": "",
   "GAL 920 KARNACK MASTIC": "",
   "GAL CP-11-1 SPRAY BRUSH GREY": "",
   "LB PLASTER OF PARIS": "",
   "HANGER": "",
   "BRUSH": "",
   "LB STAINLESS STEEL WIRE": "",
   "LB BLACK ANNEALED WIRE": "",
   "CORRUGATED JKT.": "",
   "COPPER WIRE": "",
   "GALVANIZED WIRE": "",
   "FT HEX WIRE": "",
   "BLACK GLASS FAB": "",
   "WHITE GLASS FAB FIBERGLASS MESH": "",
   "ALUM KJ SMOOTH": "",
   "EMBOSSED ALUMINUM JACKET": "",
   "ALUM JKT": "",
   "WHITE DOME CAPS": "",
   "WASHER": "",
   "WHITER ASJ PAPER": "",
   "IINSULATED MINI CUP PINS": "",
   "SELF STIC CLIPS 1000": "",
   "PERFORATED PINS WASHERS 100": "",
   "PERFORATED PINS": "",
   "SELF STICK CLIPS NW/WASH 100": "",
   "SELF ADHERE STIC CLIPS": "",
   "SELF ADHERE STIC/WASHERS 100": "",
   "SELF ADHERE STICK CLIPS..500": "",
   "INSULATED MINI CUP PINS": "",
   "PREFORATED PINS": "",
   "SELF STICK PINS 500": "",
   "STRAPPING ALUMINUM 200'": "",
   "STRAPPING ALUMINUM 900'": "",
   "ALUMINUM WING SEALS(500)": "",
   "ALUMINUM WING SEALS": "",
   "STRAPPING STAIN STEEL 200": "",
   "STRAPPING STAIN STELLA 900": "",
   "STRAPPING STAIN STEEL 900": "",
   "ST. STEEL WING SEALS": "",
   "SELF STIC W/WASHERS 100": "",
   "STAPLE GUN": "",
   "STAPLE 2619": "",
   "STAPLES": "",
   "OZ. CANVAS (38) WIDE": "",
   "REWETABLE CANVAS 60' X 50 YDS": "",
   "YDS REWETTABLE CANVAS": "",
   "REWETTABLE CANVAS": "",
   "FACE MASKS 3M # 8210..(20 per box)": "",
   "OZ. 3M SAUSAGE (CP-25)": "",
   "3M 5 GAL.CP-25 FAIREST PAIL": "",
   "Y STRAINER 3.0": "",
   "ELECTRICAL TAPE": "",
   "SMOOTH ALUMINUM TAPE": "",
   "YD BLACK DUCT TAPE": "",
   "YD GREY DUCT TAPE BEST": "",
   "FT FPS TAPE": "",
   "FT ASJ TAPE": "",
   "ASJ TAPE": "",
   "FILIMENT TAPE": "",
   "QUART PERMA WELD ADHESIVE": "",
   "QUART PERM-WELD AD -CLEAR": "",
   "P-TRAP 3 X 1 Z 2000": "",
   "P-TRAP 4 X 1 Z 2000": "",
   "PLEASE PUT INSERTS": "",
   "END CAPS Z-2000": "",
   "PVC CUT & CURL JACKET SSL": "",
   "M.L.C. Z- 2000": "",
   "M.I.T": "",
   "M.L.C. Z-200": "",
   "M.L.C. ZESTON Z-2000": "",
   "M.L.C. Z-2000": "",
   "LINE FLANG COVER": "",
   "LINE FLANGE CVR Z-200": "",
   "LINE FLANGE CVR Z-20": "",
   "LINE FLANGE CVR Z-2000": "",
   "MIL PVC JACKETING IN ROLLS": "",
   "ZESTON PVC TAPE": "",
   "L.R  90 DEG ELBOW)": "",
   "LR 90 DEG Z-2000": "",
   "L.R. 90 DEG ELBOW": "",
   "LR 90 Z-2000": "",
   "LR 90 AZ - 2000": "",
   "LR 90 DEG Z-200": "",
   "LR Z-2000": "",
   "L.R. 90 DEG EL": "",
   "TEE/VALVE": "",
   "TEE/VALVE Z-2000": "",
   "Z-2000 TEE VALVE": "",
   "TEE": "",
   "FBGLS LR W 90": "",
   "DEG ELBOW": "",
   "Z-TACKS (500) EA": "",
   "MGT TEE/VALVE": "",
   "FLANGE GATE VALVE": "",
   "MGT-90 DEG EL Z-20": "",
   "T-12 CAL-SIL P/C": "",
   "T-12 CAL SIL": "",
   "V SCORE BLOCK": "",
   "FLAT BLOCK": "",
   "V- SCORE BLOCK": "",
   "OZ CANS SPRAY ADHESIVE": "",
   "ALUM PRECISIONFIT END CAP": "",
   "ALUMINUM PRECISIONFIT": "",
   "ALUMINUM TEE (2-PCS)": "",
   "ALUMINUM SR 90 DEG EL": "",
   "SR 45": "",
   "OZ ALUMINUM CAULKING": "",
   "ALL WEATHER ALUMAGUARD": "",
   "LR 90": "",
   "B10 LAGGING SOUND SEAL": "",
   "BLACK BAGS": "",
   "H-BLOCK": "",
   "MIN/WOOL BOARD": "",
   "BUBBLE WRAP FOIL FOIL": "",
   "LBS AFLOAT INSULATING": "",
   "OZ. CAULKING GUN": "",
   "CLEAR SILICONE CAULKING": "",
   "ALUM TAPE COLD WEATHER": "",
   "DOUBLE BUBBLE WHITE CONCRETE": "",
   "DOUBLE BUBBLE (FOIL)": "",
   "DOUBLE SIDED": "",
   "15 MIL PVC JACKETING IN ROLLS": "",
   "ENDOTHERMIC MAT E 5A-4": "",
   "ET BOARD 2.8 UNFACED": "",
   "3M 1-1/2 X 24 X 25 FIREWRAP": "",
   "FILAMENT TAPE": "",
   "PLENUM FYREWRAP 3M 100": "",
   "FIREWRAP SL 1.5 (50 SQF)": "",
   "FLEX CLAD ROLL 102SF": "",
   "LEXICAL": "",
   "FOAMGLASS 45 DEG EL W": "",
   "FOAMGLASS SR 90 W": "",
   "FOAM GLASS 90 W": "",
   "FOAM GLASS PLAIN": "",
   "FOAMGLASS LR 90 DEG": "",
   "FOAMGLASS W/ASJ-SSL": "",
   "FOAMGLASS SR 90 SCRW": "",
   "FOAMGLASS SR 90 WELDED": "",
   "FOAM GLASS 45 DEG": "",
   "FOAMGLASS W/PITT COLD": "",
   "FOAMGLASS SR 90 DEG SCRW": "",
   "FOAMGLASS SR 45 DEG": "",
   "FOAMGLASS 45 DEG": "",
   "FOAMGLASS SR 90 DEG WELD": "",
   "FOAMGLASS 45 DEG WELDED": "",
   "FOAM GLASS PLAIN COLD B": "",
   "FOAMGLASS 45 DEG EL WELD": "",
   "FOAMGLASS LR 90 DEG WELD": "",
   "FOAMGLASS PLAIN (COLD)": "",
   "FOAMGLASS S.R.90 DEG": "",
   "FOAMGLASS SR 90 DEG EL": "",
   "FOAMGLASS PLAIN COLD": "",
   "FOAMGLASS PITTWR": "",
   "FOAM SPRAY 12 OZ. CAN": "",
   "NORTH 5600 SAFETY GLASSES": "",
   "BLUE PALMED COTTON GLOVES": "",
   "20 OZ. SAUSAGE GUN": "",
   "H BLOCK": "",
   "WOOD BLOCK": "",
   "IDEAL SEAL 35 1/2 777 SMOOTH": "",
   "IDEAL SEAL 35-1/2' 777 EMBOSS": "",
   "INSULFRAX": "",
   "FT PLATFORM LADDER": "",
   "FT PODIUM LADDER": "",
   "FEET LADDER": "",
   "FOOT PLATFORM LADDER": "",
   "FT PODIUM LADDER T": "",
   "GAL LCI 305 FIRESTOP SEALANT": "",
   "GAL SIL-305SL SELF-LEVELING": "",
   "SCREW HOLDER": "",
   "MINERAL BOARDS": "",
   "non as sheet": "",
   "POLYISO ASJ/SSL": "",
   "POLYISO P/C (W/ASJ)": "",
   "POLYISO W/ASL-SSL": "",
   "POLY PRO SUITS": "",
   "PREFORATED PINS W/WASHERS": "",
   "RESTOCKING FEE": "",
   "SAVING (40SQF)": "",
   "SAFING ROXUL": "",
   "STAINLESS STEEL": "",
   "SCREWS SELF TAP (1000)": "",
   "SELF STICK PINS W/WASHERS": "",
   "ACCU KNIFE SHARPENER": "",
   "SOUNDS B-20 LAG/QFA-3": "",
   "SPATULA CAULKING": "",
   "COOPER": "",
   "OZ. SASS 120 SAUSAGES STI": "",
   "OZ. LCI (320) SAUSAGE": "",
   "Description": "",
   "OZ. LCI SAUSAGE SELF LEVEL": "",
   "TAG": "",
   "OZ TUBES WHITE CAULKING": "",
   "AXLE TYVEK SUITS": "",
   "VENTURE CLAD (35 1/2 X 150) SAM": "",
   "IMAMS 1 GAL": "",
   "VAPORWICK 4 X 1 PIPECOVER": "",
   "Y-STRAINER": "",
   "Y STRAINER 3X1": "",
   "Beginning Balance": "",
   "Bounced Check Fee": "",
   "FREIGHT ": "",
   "Restocking Fee": "",
   "Exempt from Ssales Tax": "",
    "Nassau County Sales Tax": "",

}