# Generated by Django 4.2.4 on 2023-12-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_company_name_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='offline', max_length=1000, null=True),
        ),
    ]
